name: Rust CI

on: 
  push:
    branches: 'main'
    paths: '**.rs'
  pull_request: 
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cargo environment and run jobs
        uses: mirlahiji/rust-action@master
        with:
          args: make ci
